class LangData{
  String name;
  String engName;
  String image;
  bool current;
  int id;
  LangData({this.name, this.engName, this.image, this.current, this.id});
}

class Lang {

  static var english = 1;
  static var german = 2;
  static var espanol = 3;
  static var french = 4;
  static var korean = 5;

  List<LangData> langData = [
    LangData(name: 'Anglais', engName: 'English', image: 'assets/usa.png', current: false, id: english),
    LangData(name: 'Français', engName: 'French', image: 'assets/fra.png', current: false, id: french),
  ];


  Map<int, String> langEng = {
    0  : 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    1  : 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
    2  : 'Lorem ipsum',
    3  : 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ',
    10 : 'PPC DEPOT OWNER APP',
    11 : 'Don\'t have an account? Create',
    12 : 'Forgot password',
    13 : 'Let\'s start with LogIn!',
    14 : 'Login',
    15 : 'Password',
    16 : 'LOGIN',
    17 : 'Forgot password',
    18 : 'E-mail address',
    19 : 'SEND',
    20 : 'Create an Account!',
    21 : 'Login',
    22 : 'Confirm Password',
    23 : 'CREATE ACCOUNT',
    24 : 'Orders',
    25 : 'Notifications',
    26 : 'Help & Support',
    27 : 'Account',
    28 : 'Languages',
    29 : 'Sign Out',
    30 : 'App Language',
    31 : 'Log Out',
    32 : 'User Name',
    33 : 'E-mail',
    34 : 'Products',
    35 : 'Services',
    36 : 'Delivery',
    37 : 'Misc',
    38 : 'Help & support',
    39 : 'Not Have Notifications',
    40 : 'This is very important information',
    41 : 'All',
    42 : 'Preparing',
    43 : 'Ready',
    44 : 'Order ID',
    45 : 'Date',
    46 : 'Distance',
    47 : 'On Map',
    48 : 'Accept',
    49 : 'km',
    50 : 'Not Have Orders',
    51 : 'Complete',
    52 : 'Customer name',
    53 : 'Customer phone',
    54 : 'Call to Customer',
    55 : 'Back to Orders',
    56 : 'Order Details',
    57 : 'Subtotal',
    58 : 'Shopping costs',
    59 : 'Taxes',
    60 : 'Total',
    61 : 'Back to Map',
    62 : 'Online/Offline',
    63 : 'Phone',
    64 : 'Edit profile',
    65 : 'Save',
    66 : 'Cancel',
    67 : 'Enter your User Name',
    68 : 'Enter your User E-mail',
    69 : 'Enter your User Phone',
    70 : 'Change password',
    71 : 'Change',
    72 : 'Old password',
    73 : 'Enter your old password',
    74 : 'New password',
    75 : 'Enter your new password',
    76 : 'Confirm New password',
    77 : 'Open Gallery',
    78 : 'Open Camera',
    79 : 'Statistics',
    80 : 'Earnings',
    81 : 'week',
    82 : 'month',
    83 : 'Earning',
    84 : 'Rejection',
    85 : 'Reason to Reject',
    86 : 'Send',
    87 : 'Enter Reason',
    88 : 'here',
    89 : 'Map',
    90 : 'Total Earning',
    91 : 'Orders',
    92 : 'Total SHOP',
    93 : 'Total PRODUCT',
    94 : 'Foods',
    95 : 'Received',
    96 : 'On the way',
    97 : 'Delivered',
    98 : 'Status',
    99 : 'Set To',
    100 : 'Set Driver',
    101 : 'Change Driver',
    102 : 'online',
    103 : 'offline',
    104 : 'Driver',
    105 : 'My SHOP',
    106 : 'Add new Shop',
    107 : 'Delete',
    108 : 'Edit',
    109 : 'Yes, delete it!',
    110 : 'No, cancel pls!',
    111 : 'Are you sure?',
    112 : 'You will not be able to recover this item!',
    113 : 'Name',
    114 : 'Enter Shop Name',
    115 : 'Address',
    116 : 'Enter Shop Address',
    117 : 'Enter Shop Phone',
    118 : 'Latitude',
    119 : 'Enter Latitude. Example: 52.2165157',
    120 : 'Longitude',
    121 : 'Enter Longitude. Example: 2.331359',
    122 : 'Select position on Map',
    123 : 'Description',
    124 : 'Enter description',
    125 : 'Click here for select Image',
    126 : 'Select image from:',
    127 : 'Camera',
    128 : 'Gallery',
    129 : 'Select Place and Go Back',
    130 : 'Enter Shop Mobile Phone',
    131 : 'Edit Shop',
    132 : 'Edit Shop',
    133 : 'Product List',
    134 : 'My Product',
    135 : 'Category',
    136 : 'Add Product',
    137 : 'Edit Product',
    138 : 'Add new Product',
    139 : 'Enter Product Name',
    140 : 'Price',
    141 : 'Enter Product price',
    142 : 'Discount Price',
    143 : 'Enter Discount Price',
    144 : 'Ingredients',
    145 : 'Enter Ingredients',
    146 : 'Choose Product Category',
    147 : 'All',
    148 : 'Mobile Phone',
    149 : 'Menu',
    150 : 'Product',
    151 : 'Reviews',
    152 : 'Ingredients',
    153 : 'Information',
    154 : 'Enter a correct email',
    155 : ' The password is inccorect',
    156 : 'Error, Check correctly your password and username'
  };



  Map<int, String> langFrench = {
    0 : 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    1 : 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
    2 : 'Lorem ipsum',
    3 : 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ',
    10 : 'PPC SHOP OWNER',
    11 : 'Vous n\'avez pas de compte? Créer',
    12 : 'Mot de passe Oublié',
    13 : 'Connectez-vous!',
    14 : 'Se connecter',
    15 : 'Mot de passe',
    16 : 'SE CONNECTER',
    17 : 'Mot de passe Oublié',
    18 : 'Adresse Email',
    19 : 'Envoyer',
    20 : 'Créer un compte!',
    21 : 'Se connecter',
    22 : 'Confirmez le mot de passe',
    23 : 'CRÉER UN COMPTE',
    24 : 'Commandes',
    25 : 'Notifications',
    26 : 'Aide & Support',
    27 : 'Compte',
    28 : 'Langues',
    29 : 'Se déconnecter',
    30 : 'Langue de l\'application',
    31 : 'Se déconnecter',
    32 : 'Nom d\'utilisateur',
    33 : 'E-mail',
    34 : 'Produit',
    35 : 'Services',
    36 : 'Livraison',
    37 : 'Misc',
    38 : 'Aide & support',
    39 : 'Pas de Notifications',
    40 : 'C\'est une information très importante',
    41 : 'Toutes',
    42 : 'En traitement',
    43 : 'Prête',
    44 : 'Commande ID',
    45 : 'Date',
    46 : 'Distance',
    47 : 'Sur le  Map',
    48 : 'Accepté',
    49 : 'km',
    50 : 'Pas de commandes',
    51 : 'Complete',
    52 : 'Nom du Client',
    53 : 'Numéro du Client',
    54 : 'Appeler le fournisseur',
    55 : 'Retour aux commandes',
    56 : 'Détails de la commande',
    57 : 'Sous-total',
    58 : 'Frais de livraison',
    59 : 'Taxes',
    60 : 'Total',
    61 : 'Retour à la carte',
    62 : 'Connecté/déconnecté',
    63 : 'Téléphone',
    64 : 'Modifier le profil',
    65 : 'Enregistrer',
    66 : 'Annuler',
    67 : 'Entrez votre nom ',
    68 : 'Entrez votre adresse e-mail ',
    69 : 'Entrez votre numéro de téléphone ',
    70 : 'Changer le mot de passe ',
    71 : 'Changer',
    72 : 'Ancien mot de passe',
    73 : 'Entrez l\'ancien mot de passe',
    74 : 'Nouveau mot de passe',
    75 : 'Entrez le nouveau mot de passe ',
    76 : 'Confirmer le nouveau mot de passe ',
    77 : 'Ouvrir la gallerie',
    78 : 'Ouvrir la camera',
    79 : 'Statistiques',
    80 : 'Revenus',
    81 : 'semaine',
    82 : 'mois',
    83 : 'Benefices',
    84 : 'Refus',
    85 : 'Raison du refus ',
    86 : 'Envoyer',
    87 : 'Entrez la raison',
    88 : 'ici',
    89 : 'Map',
    90 : 'Benefice total',
    91 : 'Commandes',
    92 : 'Dépôt total',
    93 : 'Produit total',
    94 : 'Produit',
    95 : 'Reçue',
    96 : 'En chemin',
    97 : 'Livré',
    98 : 'Status',
    99 : 'Mis à',
    100 : 'Choisir un Livreur',
    101 : 'Changer de Livreur',
    102 : 'Enligne',
    103 : 'hors ligne',
    104 : 'Livreur',
    105 : 'Mes Dépôts',
    106 : 'Ajouter un Dépôt ',
    107 : 'Supprimer',
    108 : 'Modifier',
    109 : 'Oui, supprimez-le!',
    110 : 'Non, annulez-le',
    111 : 'Êtes-vous sûr?',
    112 : 'Vous ne pourrez pas récupérer cet objet!',
    113 : 'Nom',
    114 : 'Entrez le nom du Dépôt',
    115 : 'Adresse',
    116 : 'Entrez l\'adresse du Dépôt',
    117 : 'Entrex le numéro du Dépôt',
    118 : 'Latitude',
    119 : 'Entez la Latitude. Ex: 52.2165157',
    120 : 'Longitude',
    121 : 'Entez Longitude. Ex: 2.331359',
    122 : 'Sélectionnez la position sur la carte',
    123 : 'Description',
    124 : 'Entez la description',
    125 : 'Cliquez ici pour sélectionner l\'image',
    126 : 'Sélectionnez une image :',
    127 : 'Camera',
    128 : 'Gallerie',
    129 : 'Sélectionnez un endroit et revenir en arrière',
    130 : 'Entrez le numéro de téléphonee du Dépôt',
    131 : 'Modifier le Dépôt',
    132 : 'Modifier le Dépôt',
    133 : 'Liste de Produit',
    134 : 'Mes produits',
    135 : 'Categories',
    136 : 'Ajouter un produit',
    137 : 'Modifier un produit',
    138 : 'Ajouter un nouveau produit',
    139 : 'Entrez le nom du produit',
    140 : 'Prix',
    141 : 'Entrez le prix du produit',
    142 : 'Le prix de discount',
    143 : 'Entrez le prix de discount',
    144 : 'Ingredients',
    145 : 'Enter Ingredients',
    146 : 'Choisir la categorie de produit',
    147 : 'Toutes',
    148 : 'Numéro de téléphone',
    149 : 'Menu',
    150 : 'Produits',
    151 : 'Commentaire',
    152 : 'Ingredients',
    153 : 'Informations',
    154 : 'Entrez un email valide',
    155 : 'Le mot de passe est inccorect',
    156 : 'Erreur , Vérifiez bien votre nom d\'utilisateur et mot de passe'
  };



  //
  //
  //
  setLang(int id){
    if (id == english) {
      defaultLang = langEng;
      init = true;
    }

    if (id == french) {
      defaultLang = langFrench;
      init = true;
    }

    for (var lang in langData) {
      lang.current = false;
      if (lang.id == id)
        lang.current = true;
    }
  }

  Map<int, String> defaultLang;
  var init = false;

  String get(int id){
    if (!init) return '';
    return defaultLang[id];
  }

}

